#!/usr/bin/env node

/**
 * Generates C# source files from Lucide SVG icons for the Lucazor package.
 *
 * Output:
 *   - LucazorIcons.Part{N}.g.cs  — Static IconData properties (partial class)
 *   - LucazorIcons.Registry.g.cs — RegisterAll() method for name-based lookup
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ICONS_DIR = path.resolve(__dirname, '../../../icons');
const OUTPUT_DIR = path.resolve(__dirname, '../src/Daeha.Lucazor/Generated');
const ICONS_PER_FILE = 200;

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function toPascalCase(kebab) {
  return kebab.split('-').map((s) => s.charAt(0).toUpperCase() + s.slice(1)).join('');
}

function escapeCs(s) {
  return s.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
}

/**
 * Parses SVG child elements (path, circle, rect, line, polyline, polygon, ellipse)
 * from the inner content of an <svg> root element.
 */
function parseSvgElements(svgContent) {
  const innerMatch = svgContent.match(/<svg[^>]*>([\s\S]*)<\/svg>/);
  if (!innerMatch) return [];

  const inner = innerMatch[1].trim();
  const elements = [];

  // Self-closing tags: <path d="..." />
  const selfClosing = /<(\w+)\s+([^>]*?)\/>/g;
  let m;
  while ((m = selfClosing.exec(inner)) !== null) {
    elements.push({ tag: m[1], attrs: parseAttributes(m[2]) });
  }

  // Non-self-closing tags (rare): <text x="0">...</text>
  const openClose = /<(\w+)\s+([^>]*?)>[^<]*<\/\1>/g;
  while ((m = openClose.exec(inner)) !== null) {
    elements.push({ tag: m[1], attrs: parseAttributes(m[2]) });
  }

  return elements;
}

function parseAttributes(attrString) {
  const attrs = {};
  const re = /([\w-]+)="([^"]*)"/g;
  let m;
  while ((m = re.exec(attrString)) !== null) {
    attrs[m[1]] = m[2];
  }
  return attrs;
}

// ---------------------------------------------------------------------------
// Code generation
// ---------------------------------------------------------------------------

const FILE_HEADER = `// <auto-generated>
// This file was generated by the Lucazor icon generator.
// Do not edit this file directly.
// </auto-generated>

using System.Collections.Generic;
using System.Collections.ObjectModel;

namespace Lucazor;

`;

function generateIconProperty(iconName, elements) {
  const pascal = toPascalCase(iconName);
  const elems = elements.map((el) => {
    const pairs = Object.entries(el.attrs)
      .map(([k, v]) => `                { "${escapeCs(k)}", "${escapeCs(v)}" }`)
      .join(',\n');
    return `            new IconElement("${el.tag}", new ReadOnlyDictionary<string, string>(new Dictionary<string, string>\n            {\n${pairs}\n            }))`;
  });

  return `        public static IconData ${pascal} { get; } = new IconData("${iconName}", new IconElement[]
        {
${elems.join(',\n')}
        });`;
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

fs.mkdirSync(OUTPUT_DIR, { recursive: true });

// Clean previous generated files
for (const f of fs.readdirSync(OUTPUT_DIR)) {
  if (f.endsWith('.g.cs')) {
    fs.unlinkSync(path.join(OUTPUT_DIR, f));
  }
}

const svgFiles = fs.readdirSync(ICONS_DIR).filter((f) => f.endsWith('.svg')).sort();
console.log(`Found ${svgFiles.length} SVG icons`);

const allIcons = []; // { name, pascal }

// Split into chunks
const chunks = [];
for (let i = 0; i < svgFiles.length; i += ICONS_PER_FILE) {
  chunks.push(svgFiles.slice(i, i + ICONS_PER_FILE));
}

for (let ci = 0; ci < chunks.length; ci++) {
  const properties = [];

  for (const file of chunks[ci]) {
    const iconName = file.replace('.svg', '');
    const svgContent = fs.readFileSync(path.join(ICONS_DIR, file), 'utf-8');
    const elements = parseSvgElements(svgContent);

    if (elements.length === 0) {
      console.warn(`  ⚠ No elements in ${file}, skipping`);
      continue;
    }

    properties.push(generateIconProperty(iconName, elements));
    allIcons.push({ name: iconName, pascal: toPascalCase(iconName) });
  }

  const content = `${FILE_HEADER}public static partial class LucazorIcons
{
${properties.join('\n\n')}
}
`;

  const fileName = `LucazorIcons.Part${ci + 1}.g.cs`;
  fs.writeFileSync(path.join(OUTPUT_DIR, fileName), content, 'utf-8');
  console.log(`  ${fileName} — ${chunks[ci].length} icons`);
}

// Generate registry initializer
const registrations = allIcons
  .map(({ name, pascal }) => `            LucazorIconRegistry.Register("${name}", ${pascal});`)
  .join('\n');

const registryContent = `${FILE_HEADER}public static partial class LucazorIcons
{
    private static volatile bool _initialized;
    private static readonly object _lock = new object();

    /// <summary>
    /// Registers all icons in the <see cref="LucazorIconRegistry"/> for name-based lookup.
    /// Called automatically on first registry access.
    /// </summary>
    public static void RegisterAll()
    {
        if (_initialized) return;
        lock (_lock)
        {
            if (_initialized) return;

${registrations}

            _initialized = true;
        }
    }
}
`;

fs.writeFileSync(path.join(OUTPUT_DIR, 'LucazorIcons.Registry.g.cs'), registryContent, 'utf-8');

console.log(`\nTotal: ${allIcons.length} icons in ${chunks.length} part file(s) + registry`);
