#!/usr/bin/env node

/**
 * Generates C# source files from Lucide SVG icons.
 * Produces:
 *   - LucideIcons.Generated.cs (static properties for each icon)
 *   - Individual icon data registered in the icon registry
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const iconsDir = path.resolve(__dirname, '../../../icons');
const outputDir = path.resolve(__dirname, '../src/Lucide.Net/Generated');

function toPascalCase(str) {
  return str
    .split('-')
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
    .join('');
}

function escapeXml(s) {
  return s.replace(/&/g, '&amp;').replace(/"/g, '\\"');
}

function parseSvgChildren(svgContent) {
  // Extract child elements from the SVG (everything inside the root <svg> tag)
  const innerMatch = svgContent.match(/<svg[^>]*>([\s\S]*)<\/svg>/);
  if (!innerMatch) return [];

  const inner = innerMatch[1].trim();
  const elements = [];

  // Match self-closing tags like <path ... />, <circle ... />, <rect ... />, etc.
  const tagRegex = /<(\w+)\s+([^>]*?)\/>/g;
  let match;
  while ((match = tagRegex.exec(inner)) !== null) {
    const tag = match[1];
    const attrsStr = match[2].trim();
    const attrs = {};

    const attrRegex = /(\w[\w-]*)="([^"]*)"/g;
    let attrMatch;
    while ((attrMatch = attrRegex.exec(attrsStr)) !== null) {
      attrs[attrMatch[1]] = attrMatch[2];
    }

    elements.push({ tag, attrs });
  }

  // Also match non-self-closing tags (rare but possible)
  const openTagRegex = /<(\w+)\s+([^>]*?)>([^<]*)<\/\1>/g;
  while ((match = openTagRegex.exec(inner)) !== null) {
    const tag = match[1];
    const attrsStr = match[2].trim();
    const attrs = {};

    const attrRegex = /(\w[\w-]*)="([^"]*)"/g;
    let attrMatch;
    while ((attrMatch = attrRegex.exec(attrsStr)) !== null) {
      attrs[attrMatch[1]] = attrMatch[2];
    }

    elements.push({ tag, attrs });
  }

  return elements;
}

function generateIconMethod(iconName, elements) {
  const pascalName = toPascalCase(iconName);
  const elementsCode = elements
    .map((el) => {
      const attrsDict = Object.entries(el.attrs)
        .map(([k, v]) => `            { "${k}", "${escapeXml(v)}" }`)
        .join(',\n');
      return `        new IconElement("${el.tag}", new Dictionary<string, string>\n        {\n${attrsDict}\n        })`;
    })
    .join(',\n');

  return `    /// <summary>
    /// Gets the ${pascalName} icon.
    /// </summary>
    public static IconData ${pascalName} { get; } = new IconData("${iconName}", new IconElement[]
    {
${elementsCode}
    });`;
}

// Main
if (!fs.existsSync(outputDir)) {
  fs.mkdirSync(outputDir, { recursive: true });
}

const svgFiles = fs
  .readdirSync(iconsDir)
  .filter((f) => f.endsWith('.svg'))
  .sort();

console.log(`Found ${svgFiles.length} SVG icons`);

// Split into chunks to avoid huge single files
const CHUNK_SIZE = 200;
const chunks = [];
for (let i = 0; i < svgFiles.length; i += CHUNK_SIZE) {
  chunks.push(svgFiles.slice(i, i + CHUNK_SIZE));
}

const allIconNames = [];

for (let chunkIdx = 0; chunkIdx < chunks.length; chunkIdx++) {
  const chunk = chunks[chunkIdx];
  const methods = [];

  for (const file of chunk) {
    const iconName = file.replace('.svg', '');
    const svgContent = fs.readFileSync(path.join(iconsDir, file), 'utf-8');
    const elements = parseSvgChildren(svgContent);

    if (elements.length === 0) {
      console.warn(`Warning: No elements found in ${file}`);
      continue;
    }

    methods.push(generateIconMethod(iconName, elements));
    allIconNames.push(iconName);
  }

  const classContent = `// <auto-generated>
// This file was generated by the Lucide icon generator.
// Do not edit this file directly.
// </auto-generated>

using System.Collections.Generic;

namespace Lucide;

public static partial class LucideIcons
{
${methods.join('\n\n')}
}
`;

  const fileName = `LucideIcons.Part${chunkIdx + 1}.g.cs`;
  fs.writeFileSync(path.join(outputDir, fileName), classContent, 'utf-8');
  console.log(`Generated ${fileName} with ${chunk.length} icons`);
}

// Generate registry initializer
const registrations = allIconNames
  .map((name) => `        LucideIconRegistry.Register("${name}", LucideIcons.${toPascalCase(name)});`)
  .join('\n');

const registryInit = `// <auto-generated>
// This file was generated by the Lucide icon generator.
// Do not edit this file directly.
// </auto-generated>

namespace Lucide;

public static partial class LucideIcons
{
    private static bool _initialized;
    private static readonly object _lock = new object();

    /// <summary>
    /// Registers all icons in the LucideIconRegistry for name-based lookup.
    /// Called automatically on first registry access, or call explicitly.
    /// </summary>
    public static void RegisterAll()
    {
        if (_initialized) return;
        lock (_lock)
        {
            if (_initialized) return;

${registrations}

            _initialized = true;
        }
    }
}
`;

fs.writeFileSync(path.join(outputDir, 'LucideIcons.Registry.g.cs'), registryInit, 'utf-8');

console.log(`\nTotal: ${allIconNames.length} icons generated in ${chunks.length} file(s)`);
