language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js: 8
before_script:
  - npm prune
script:
  - npm run all
after_success:
  - npx codecov
  - npx babel-node ./bin/sync-algolia.js
deploy:
  provider: script
  skip_cleanup: true
  script:
    - npx semantic-release
