import getVueComponent from './getters/getVueComponent';

import ActivityNode from './icons/activity';
import AirplayNode from './icons/airplay';
import AlertCircleNode from './icons/alert-circle';
import AlertOctagonNode from './icons/alert-octagon';
import AlertTriangleNode from './icons/alert-triangle';
import AlignCenterNode from './icons/align-center';
import AlignJustifyNode from './icons/align-justify';
import AlignLeftNode from './icons/align-left';
import AlignRightNode from './icons/align-right';
import AnchorNode from './icons/anchor';
import ApertureNode from './icons/aperture';
import ArchiveNode from './icons/archive';
import ArrowDownCircleNode from './icons/arrow-down-circle';
import ArrowDownLeftNode from './icons/arrow-down-left';
import ArrowDownRightNode from './icons/arrow-down-right';
import ArrowDownNode from './icons/arrow-down';
import ArrowLeftCircleNode from './icons/arrow-left-circle';
import ArrowLeftNode from './icons/arrow-left';
import ArrowRightCircleNode from './icons/arrow-right-circle';
import ArrowRightNode from './icons/arrow-right';
import ArrowUpCircleNode from './icons/arrow-up-circle';
import ArrowUpLeftNode from './icons/arrow-up-left';
import ArrowUpRightNode from './icons/arrow-up-right';
import ArrowUpNode from './icons/arrow-up';
import AtSignNode from './icons/at-sign';
import AwardNode from './icons/award';
import BarChart2Node from './icons/bar-chart-2';
import BarChartNode from './icons/bar-chart';
import BatteryChargingNode from './icons/battery-charging';
import BatteryFullNode from './icons/battery-full';
import BatteryLowNode from './icons/battery-low';
import BatteryMediumNode from './icons/battery-medium';
import BatteryNode from './icons/battery';
import BellOffNode from './icons/bell-off';
import BellNode from './icons/bell';
import BluetoothNode from './icons/bluetooth';
import BoldNode from './icons/bold';
import BookOpenNode from './icons/book-open';
import BookNode from './icons/book';
import BookmarkNode from './icons/bookmark';
import BoxNode from './icons/box';
import BriefcaseNode from './icons/briefcase';
import CalendarNode from './icons/calendar';
import CameraOffNode from './icons/camera-off';
import CameraNode from './icons/camera';
import CastNode from './icons/cast';
import CheckCircleNode from './icons/check-circle';
import CheckSquareNode from './icons/check-square';
import CheckNode from './icons/check';
import ChevronDownNode from './icons/chevron-down';
import ChevronLeftNode from './icons/chevron-left';
import ChevronRightNode from './icons/chevron-right';
import ChevronUpNode from './icons/chevron-up';
import ChevronsDownNode from './icons/chevrons-down';
import ChevronsLeftNode from './icons/chevrons-left';
import ChevronsRightNode from './icons/chevrons-right';
import ChevronsUpNode from './icons/chevrons-up';
import ChromeNode from './icons/chrome';
import CircleNode from './icons/circle';
import ClipboardNode from './icons/clipboard';
import ClockNode from './icons/clock';
import CloudDrizzleNode from './icons/cloud-drizzle';
import CloudLightningNode from './icons/cloud-lightning';
import CloudOffNode from './icons/cloud-off';
import CloudRainNode from './icons/cloud-rain';
import CloudSnowNode from './icons/cloud-snow';
import CloudNode from './icons/cloud';
import CodeNode from './icons/code';
import CodepenNode from './icons/codepen';
import CodesandboxNode from './icons/codesandbox';
import CoffeeNode from './icons/coffee';
import ColumnsNode from './icons/columns';
import CommandNode from './icons/command';
import CompassNode from './icons/compass';
import ContactNode from './icons/contact';
import ContrastNode from './icons/contrast';
import CopyNode from './icons/copy';
import CopyleftNode from './icons/copyleft';
import CopyrightNode from './icons/copyright';
import CornerDownLeftNode from './icons/corner-down-left';
import CornerDownRightNode from './icons/corner-down-right';
import CornerLeftDownNode from './icons/corner-left-down';
import CornerLeftUpNode from './icons/corner-left-up';
import CornerRightDownNode from './icons/corner-right-down';
import CornerRightUpNode from './icons/corner-right-up';
import CornerUpLeftNode from './icons/corner-up-left';
import CornerUpRightNode from './icons/corner-up-right';
import CpuNode from './icons/cpu';
import CreditCardNode from './icons/credit-card';
import CropNode from './icons/crop';
import CrosshairNode from './icons/crosshair';
import DatabaseNode from './icons/database';
import DeleteNode from './icons/delete';
import DiscNode from './icons/disc';
import DivideCircleNode from './icons/divide-circle';
import DivideSquareNode from './icons/divide-square';
import DivideNode from './icons/divide';
import DollarSignNode from './icons/dollar-sign';
import DownloadCloudNode from './icons/download-cloud';
import DownloadNode from './icons/download';
import DribbbleNode from './icons/dribbble';
import DropletNode from './icons/droplet';
import Edit2Node from './icons/edit-2';
import Edit3Node from './icons/edit-3';
import EditNode from './icons/edit';
import ExternalLinkNode from './icons/external-link';
import EyeOffNode from './icons/eye-off';
import EyeNode from './icons/eye';
import FacebookNode from './icons/facebook';
import FastForwardNode from './icons/fast-forward';
import FeatherNode from './icons/feather';
import FigmaNode from './icons/figma';
import FileMinusNode from './icons/file-minus';
import FilePlusNode from './icons/file-plus';
import FileTextNode from './icons/file-text';
import FileNode from './icons/file';
import FilmNode from './icons/film';
import FilterNode from './icons/filter';
import FlagNode from './icons/flag';
import FolderMinusNode from './icons/folder-minus';
import FolderPlusNode from './icons/folder-plus';
import FolderNode from './icons/folder';
import FramerNode from './icons/framer';
import FrownNode from './icons/frown';
import Gamepad2Node from './icons/gamepad-2';
import GamepadNode from './icons/gamepad';
import GiftNode from './icons/gift';
import GitBranchNode from './icons/git-branch';
import GitCommitNode from './icons/git-commit';
import GitMergeNode from './icons/git-merge';
import GitPullRequestNode from './icons/git-pull-request';
import GitHubNode from './icons/github';
import GitlabNode from './icons/gitlab';
import GlobeNode from './icons/globe';
import GridNode from './icons/grid';
import GripHorizontalNode from './icons/grip-horizontal';
import GripVerticalNode from './icons/grip-vertical';
import HardDriveNode from './icons/hard-drive';
import HashNode from './icons/hash';
import HeadphonesNode from './icons/headphones';
import HeartNode from './icons/heart';
import HelpCircleNode from './icons/help-circle';
import HexagonNode from './icons/hexagon';
import HighlighterNode from './icons/highlighter';
import HomeNode from './icons/home';
import ImageNode from './icons/image';
import InboxNode from './icons/inbox';
import InfoNode from './icons/info';
import InstagramNode from './icons/instagram';
import ItalicNode from './icons/italic';
import KeyNode from './icons/key';
import LanguagesNode from './icons/languages';
import LayersNode from './icons/layers';
import LayoutNode from './icons/layout';
import LifeBuoyNode from './icons/life-buoy';
import Link2OffNode from './icons/link-2-off';
import Link2Node from './icons/link-2';
import LinkNode from './icons/link';
import LinkedinNode from './icons/linkedin';
import ListNode from './icons/list';
import LoaderNode from './icons/loader';
import LockNode from './icons/lock';
import LogInNode from './icons/log-in';
import LogOutNode from './icons/log-out';
import MailNode from './icons/mail';
import MapPinNode from './icons/map-pin';
import MapNode from './icons/map';
import Maximize2Node from './icons/maximize-2';
import MaximizeNode from './icons/maximize';
import MehNode from './icons/meh';
import MenuNode from './icons/menu';
import MessageCircleNode from './icons/message-circle';
import MessageSquareNode from './icons/message-square';
import MicOffNode from './icons/mic-off';
import MicNode from './icons/mic';
import Minimize2Node from './icons/minimize-2';
import MinimizeNode from './icons/minimize';
import MinusCircleNode from './icons/minus-circle';
import MinusSquareNode from './icons/minus-square';
import MinusNode from './icons/minus';
import MonitorNode from './icons/monitor';
import MoonNode from './icons/moon';
import MoreHorizontalNode from './icons/more-horizontal';
import MoreVerticalNode from './icons/more-vertical';
import MousePointerNode from './icons/mouse-pointer';
import MoveNode from './icons/move';
import MusicNode from './icons/music';
import Navigation2Node from './icons/navigation-2';
import NavigationNode from './icons/navigation';
import NetworkNode from './icons/network';
import OctagonNode from './icons/octagon';
import PackageNode from './icons/package';
import PaperclipNode from './icons/paperclip';
import PauseCircleNode from './icons/pause-circle';
import PauseNode from './icons/pause';
import PenToolNode from './icons/pen-tool';
import PercentNode from './icons/percent';
import PhoneCallNode from './icons/phone-call';
import PhoneForwardedNode from './icons/phone-forwarded';
import PhoneIncomingNode from './icons/phone-incoming';
import PhoneMissedNode from './icons/phone-missed';
import PhoneOffNode from './icons/phone-off';
import PhoneOutgoingNode from './icons/phone-outgoing';
import PhoneNode from './icons/phone';
import PieChartNode from './icons/pie-chart';
import PlayCircleNode from './icons/play-circle';
import PlayNode from './icons/play';
import PlusCircleNode from './icons/plus-circle';
import PlusSquareNode from './icons/plus-square';
import PlusNode from './icons/plus';
import PocketNode from './icons/pocket';
import PowerNode from './icons/power';
import PrinterNode from './icons/printer';
import RadioNode from './icons/radio';
import RefreshCcwNode from './icons/refresh-ccw';
import RefreshCwNode from './icons/refresh-cw';
import RepeatNode from './icons/repeat';
import RewindNode from './icons/rewind';
import RotateCcwNode from './icons/rotate-ccw';
import RotateCwNode from './icons/rotate-cw';
import RssNode from './icons/rss';
import SaveNode from './icons/save';
import ScissorsNode from './icons/scissors';
import ScreenShareOffNode from './icons/screen-share-off';
import ScreenShareNode from './icons/screen-share';
import SearchNode from './icons/search';
import SendNode from './icons/send';
import ServerNode from './icons/server';
import SettingsNode from './icons/settings';
import Share2Node from './icons/share-2';
import ShareNode from './icons/share';
import ShieldOffNode from './icons/shield-off';
import ShieldNode from './icons/shield';
import ShoppingBagNode from './icons/shopping-bag';
import ShoppingCartNode from './icons/shopping-cart';
import ShuffleNode from './icons/shuffle';
import SidebarNode from './icons/sidebar';
import SkipBackNode from './icons/skip-back';
import SkipForwardNode from './icons/skip-forward';
import SlackNode from './icons/slack';
import SlashNode from './icons/slash';
import SlidersNode from './icons/sliders';
import SmartphoneNode from './icons/smartphone';
import SmileNode from './icons/smile';
import SnowflakeNode from './icons/snowflake';
import SortAscNode from './icons/sort-asc';
import SortDescNode from './icons/sort-desc';
import SpeakerNode from './icons/speaker';
import SquareNode from './icons/square';
import StarNode from './icons/star';
import StopCircleNode from './icons/stop-circle';
import StrikethroughNode from './icons/strikethrough';
import SunNode from './icons/sun';
import SunriseNode from './icons/sunrise';
import SunsetNode from './icons/sunset';
import SwitchCameraNode from './icons/switch-camera';
import TabletNode from './icons/tablet';
import TagNode from './icons/tag';
import TargetNode from './icons/target';
import TerminalNode from './icons/terminal';
import ThermometerNode from './icons/thermometer';
import ThumbsDownNode from './icons/thumbs-down';
import ThumbsUpNode from './icons/thumbs-up';
import ToggleLeftNode from './icons/toggle-left';
import ToggleRightNode from './icons/toggle-right';
import ToolNode from './icons/tool';
import Trash2Node from './icons/trash-2';
import TrashNode from './icons/trash';
import TrelloNode from './icons/trello';
import TrendingDownNode from './icons/trending-down';
import TrendingUpNode from './icons/trending-up';
import TriangleNode from './icons/triangle';
import TruckNode from './icons/truck';
import TvNode from './icons/tv';
import TwitchNode from './icons/twitch';
import TwitterNode from './icons/twitter';
import TypeNode from './icons/type';
import UmbrellaNode from './icons/umbrella';
import UnderlineNode from './icons/underline';
import Unlink2Node from './icons/unlink-2';
import UnlinkNode from './icons/unlink';
import UnlockNode from './icons/unlock';
import UploadCloudNode from './icons/upload-cloud';
import UploadNode from './icons/upload';
import UserCheckNode from './icons/user-check';
import UserMinusNode from './icons/user-minus';
import UserPlusNode from './icons/user-plus';
import UserXNode from './icons/user-x';
import UserNode from './icons/user';
import UsersNode from './icons/users';
import VideoOffNode from './icons/video-off';
import VideoNode from './icons/video';
import VoicemailNode from './icons/voicemail';
import Volume1Node from './icons/volume-1';
import Volume2Node from './icons/volume-2';
import VolumeXNode from './icons/volume-x';
import VolumeNode from './icons/volume';
import WatchNode from './icons/watch';
import WifiOffNode from './icons/wifi-off';
import WifiNode from './icons/wifi';
import WindNode from './icons/wind';
import XCircleNode from './icons/x-circle';
import XOctagonNode from './icons/x-octagon';
import XSquareNode from './icons/x-square';
import XNode from './icons/x';
import YoutubeNode from './icons/youtube';
import ZapOffNode from './icons/zap-off';
import ZapNode from './icons/zap';
import ZoomInNode from './icons/zoom-in';
import ZoomOutNode from './icons/zoom-out';

export const Activity = getVueComponent('Activity', ActivityNode);
export const Airplay = getVueComponent('Airplay', AirplayNode);
export const AlertCircle = getVueComponent('AlertCircle', AlertCircleNode);
export const AlertOctagon = getVueComponent('AlertOctagon', AlertOctagonNode);
export const AlertTriangle = getVueComponent('AlertTriangle', AlertTriangleNode);
export const AlignCenter = getVueComponent('AlignCenter', AlignCenterNode);
export const AlignJustify = getVueComponent('AlignJustify', AlignJustifyNode);
export const AlignLeft = getVueComponent('AlignLeft', AlignLeftNode);
export const AlignRight = getVueComponent('AlignRight', AlignRightNode);
export const Anchor = getVueComponent('Anchor', AnchorNode);
export const Aperture = getVueComponent('Aperture', ApertureNode);
export const Archive = getVueComponent('Archive', ArchiveNode);
export const ArrowDownCircle = getVueComponent('ArrowDownCircle', ArrowDownCircleNode);
export const ArrowDownLeft = getVueComponent('ArrowDownLeft', ArrowDownLeftNode);
export const ArrowDownRight = getVueComponent('ArrowDownRight', ArrowDownRightNode);
export const ArrowDown = getVueComponent('ArrowDown', ArrowDownNode);
export const ArrowLeftCircle = getVueComponent('ArrowLeftCircle', ArrowLeftCircleNode);
export const ArrowLeft = getVueComponent('ArrowLeft', ArrowLeftNode);
export const ArrowRightCircle = getVueComponent('ArrowRightCircle', ArrowRightCircleNode);
export const ArrowRight = getVueComponent('ArrowRight', ArrowRightNode);
export const ArrowUpCircle = getVueComponent('ArrowUpCircle', ArrowUpCircleNode);
export const ArrowUpLeft = getVueComponent('ArrowUpLeft', ArrowUpLeftNode);
export const ArrowUpRight = getVueComponent('ArrowUpRight', ArrowUpRightNode);
export const ArrowUp = getVueComponent('ArrowUp', ArrowUpNode);
export const AtSign = getVueComponent('AtSign', AtSignNode);
export const Award = getVueComponent('Award', AwardNode);
export const BarChart2 = getVueComponent('BarChart2', BarChart2Node);
export const BarChart = getVueComponent('BarChart', BarChartNode);
export const BatteryCharging = getVueComponent('BatteryCharging', BatteryChargingNode);
export const BatteryFull = getVueComponent('BatteryFull', BatteryFullNode);
export const BatteryLow = getVueComponent('BatteryLow', BatteryLowNode);
export const BatteryMedium = getVueComponent('BatteryMedium', BatteryMediumNode);
export const Battery = getVueComponent('Battery', BatteryNode);
export const BellOff = getVueComponent('BellOff', BellOffNode);
export const Bell = getVueComponent('Bell', BellNode);
export const Bluetooth = getVueComponent('Bluetooth', BluetoothNode);
export const Bold = getVueComponent('Bold', BoldNode);
export const BookOpen = getVueComponent('BookOpen', BookOpenNode);
export const Book = getVueComponent('Book', BookNode);
export const Bookmark = getVueComponent('Bookmark', BookmarkNode);
export const Box = getVueComponent('Box', BoxNode);
export const Briefcase = getVueComponent('Briefcase', BriefcaseNode);
export const Calendar = getVueComponent('Calendar', CalendarNode);
export const CameraOff = getVueComponent('CameraOff', CameraOffNode);
export const Camera = getVueComponent('Camera', CameraNode);
export const Cast = getVueComponent('Cast', CastNode);
export const CheckCircle = getVueComponent('CheckCircle', CheckCircleNode);
export const CheckSquare = getVueComponent('CheckSquare', CheckSquareNode);
export const Check = getVueComponent('Check', CheckNode);
export const ChevronDown = getVueComponent('ChevronDown', ChevronDownNode);
export const ChevronLeft = getVueComponent('ChevronLeft', ChevronLeftNode);
export const ChevronRight = getVueComponent('ChevronRight', ChevronRightNode);
export const ChevronUp = getVueComponent('ChevronUp', ChevronUpNode);
export const ChevronsDown = getVueComponent('ChevronsDown', ChevronsDownNode);
export const ChevronsLeft = getVueComponent('ChevronsLeft', ChevronsLeftNode);
export const ChevronsRight = getVueComponent('ChevronsRight', ChevronsRightNode);
export const ChevronsUp = getVueComponent('ChevronsUp', ChevronsUpNode);
export const Chrome = getVueComponent('Chrome', ChromeNode);
export const Circle = getVueComponent('Circle', CircleNode);
export const Clipboard = getVueComponent('Clipboard', ClipboardNode);
export const Clock = getVueComponent('Clock', ClockNode);
export const CloudDrizzle = getVueComponent('CloudDrizzle', CloudDrizzleNode);
export const CloudLightning = getVueComponent('CloudLightning', CloudLightningNode);
export const CloudOff = getVueComponent('CloudOff', CloudOffNode);
export const CloudRain = getVueComponent('CloudRain', CloudRainNode);
export const CloudSnow = getVueComponent('CloudSnow', CloudSnowNode);
export const Cloud = getVueComponent('Cloud', CloudNode);
export const Code = getVueComponent('Code', CodeNode);
export const Codepen = getVueComponent('Codepen', CodepenNode);
export const Codesandbox = getVueComponent('Codesandbox', CodesandboxNode);
export const Coffee = getVueComponent('Coffee', CoffeeNode);
export const Columns = getVueComponent('Columns', ColumnsNode);
export const Command = getVueComponent('Command', CommandNode);
export const Compass = getVueComponent('Compass', CompassNode);
export const Contact = getVueComponent('Contact', ContactNode);
export const Contrast = getVueComponent('Contrast', ContrastNode);
export const Copy = getVueComponent('Copy', CopyNode);
export const Copyleft = getVueComponent('Copyleft', CopyleftNode);
export const Copyright = getVueComponent('Copyright', CopyrightNode);
export const CornerDownLeft = getVueComponent('CornerDownLeft', CornerDownLeftNode);
export const CornerDownRight = getVueComponent('CornerDownRight', CornerDownRightNode);
export const CornerLeftDown = getVueComponent('CornerLeftDown', CornerLeftDownNode);
export const CornerLeftUp = getVueComponent('CornerLeftUp', CornerLeftUpNode);
export const CornerRightDown = getVueComponent('CornerRightDown', CornerRightDownNode);
export const CornerRightUp = getVueComponent('CornerRightUp', CornerRightUpNode);
export const CornerUpLeft = getVueComponent('CornerUpLeft', CornerUpLeftNode);
export const CornerUpRight = getVueComponent('CornerUpRight', CornerUpRightNode);
export const Cpu = getVueComponent('Cpu', CpuNode);
export const CreditCard = getVueComponent('CreditCard', CreditCardNode);
export const Crop = getVueComponent('Crop', CropNode);
export const Crosshair = getVueComponent('Crosshair', CrosshairNode);
export const Database = getVueComponent('Database', DatabaseNode);
export const Delete = getVueComponent('Delete', DeleteNode);
export const Disc = getVueComponent('Disc', DiscNode);
export const DivideCircle = getVueComponent('DivideCircle', DivideCircleNode);
export const DivideSquare = getVueComponent('DivideSquare', DivideSquareNode);
export const Divide = getVueComponent('Divide', DivideNode);
export const DollarSign = getVueComponent('DollarSign', DollarSignNode);
export const DownloadCloud = getVueComponent('DownloadCloud', DownloadCloudNode);
export const Download = getVueComponent('Download', DownloadNode);
export const Dribbble = getVueComponent('Dribbble', DribbbleNode);
export const Droplet = getVueComponent('Droplet', DropletNode);
export const Edit2 = getVueComponent('Edit2', Edit2Node);
export const Edit3 = getVueComponent('Edit3', Edit3Node);
export const Edit = getVueComponent('Edit', EditNode);
export const ExternalLink = getVueComponent('ExternalLink', ExternalLinkNode);
export const EyeOff = getVueComponent('EyeOff', EyeOffNode);
export const Eye = getVueComponent('Eye', EyeNode);
export const Facebook = getVueComponent('Facebook', FacebookNode);
export const FastForward = getVueComponent('FastForward', FastForwardNode);
export const Feather = getVueComponent('Feather', FeatherNode);
export const Figma = getVueComponent('Figma', FigmaNode);
export const FileMinus = getVueComponent('FileMinus', FileMinusNode);
export const FilePlus = getVueComponent('FilePlus', FilePlusNode);
export const FileText = getVueComponent('FileText', FileTextNode);
export const File = getVueComponent('File', FileNode);
export const Film = getVueComponent('Film', FilmNode);
export const Filter = getVueComponent('Filter', FilterNode);
export const Flag = getVueComponent('Flag', FlagNode);
export const FolderMinus = getVueComponent('FolderMinus', FolderMinusNode);
export const FolderPlus = getVueComponent('FolderPlus', FolderPlusNode);
export const Folder = getVueComponent('Folder', FolderNode);
export const Framer = getVueComponent('Framer', FramerNode);
export const Frown = getVueComponent('Frown', FrownNode);
export const Gamepad2 = getVueComponent('Gamepad2', Gamepad2Node);
export const Gamepad = getVueComponent('Gamepad', GamepadNode);
export const Gift = getVueComponent('Gift', GiftNode);
export const GitBranch = getVueComponent('GitBranch', GitBranchNode);
export const GitCommit = getVueComponent('GitCommit', GitCommitNode);
export const GitMerge = getVueComponent('GitMerge', GitMergeNode);
export const GitPullRequest = getVueComponent('GitPullRequest', GitPullRequestNode);
export const GitHub = getVueComponent('GitHub', GitHubNode);
export const Gitlab = getVueComponent('Gitlab', GitlabNode);
export const Globe = getVueComponent('Globe', GlobeNode);
export const Grid = getVueComponent('Grid', GridNode);
export const GripHorizontal = getVueComponent('GripHorizontal', GripHorizontalNode);
export const GripVertical = getVueComponent('GripVertical', GripVerticalNode);
export const HardDrive = getVueComponent('HardDrive', HardDriveNode);
export const Hash = getVueComponent('Hash', HashNode);
export const Headphones = getVueComponent('Headphones', HeadphonesNode);
export const Heart = getVueComponent('Heart', HeartNode);
export const HelpCircle = getVueComponent('HelpCircle', HelpCircleNode);
export const Hexagon = getVueComponent('Hexagon', HexagonNode);
export const Highlighter = getVueComponent('Highlighter', HighlighterNode);
export const Home = getVueComponent('Home', HomeNode);
export const Image = getVueComponent('Image', ImageNode);
export const Inbox = getVueComponent('Inbox', InboxNode);
export const Info = getVueComponent('Info', InfoNode);
export const Instagram = getVueComponent('Instagram', InstagramNode);
export const Italic = getVueComponent('Italic', ItalicNode);
export const Key = getVueComponent('Key', KeyNode);
export const Languages = getVueComponent('Languages', LanguagesNode);
export const Layers = getVueComponent('Layers', LayersNode);
export const Layout = getVueComponent('Layout', LayoutNode);
export const LifeBuoy = getVueComponent('LifeBuoy', LifeBuoyNode);
export const Link2Off = getVueComponent('Link2Off', Link2OffNode);
export const Link2 = getVueComponent('Link2', Link2Node);
export const Link = getVueComponent('Link', LinkNode);
export const Linkedin = getVueComponent('Linkedin', LinkedinNode);
export const List = getVueComponent('List', ListNode);
export const Loader = getVueComponent('Loader', LoaderNode);
export const Lock = getVueComponent('Lock', LockNode);
export const LogIn = getVueComponent('LogIn', LogInNode);
export const LogOut = getVueComponent('LogOut', LogOutNode);
export const Mail = getVueComponent('Mail', MailNode);
export const MapPin = getVueComponent('MapPin', MapPinNode);
export const Map = getVueComponent('Map', MapNode);
export const Maximize2 = getVueComponent('Maximize2', Maximize2Node);
export const Maximize = getVueComponent('Maximize', MaximizeNode);
export const Meh = getVueComponent('Meh', MehNode);
export const Menu = getVueComponent('Menu', MenuNode);
export const MessageCircle = getVueComponent('MessageCircle', MessageCircleNode);
export const MessageSquare = getVueComponent('MessageSquare', MessageSquareNode);
export const MicOff = getVueComponent('MicOff', MicOffNode);
export const Mic = getVueComponent('Mic', MicNode);
export const Minimize2 = getVueComponent('Minimize2', Minimize2Node);
export const Minimize = getVueComponent('Minimize', MinimizeNode);
export const MinusCircle = getVueComponent('MinusCircle', MinusCircleNode);
export const MinusSquare = getVueComponent('MinusSquare', MinusSquareNode);
export const Minus = getVueComponent('Minus', MinusNode);
export const Monitor = getVueComponent('Monitor', MonitorNode);
export const Moon = getVueComponent('Moon', MoonNode);
export const MoreHorizontal = getVueComponent('MoreHorizontal', MoreHorizontalNode);
export const MoreVertical = getVueComponent('MoreVertical', MoreVerticalNode);
export const MousePointer = getVueComponent('MousePointer', MousePointerNode);
export const Move = getVueComponent('Move', MoveNode);
export const Music = getVueComponent('Music', MusicNode);
export const Navigation2 = getVueComponent('Navigation2', Navigation2Node);
export const Navigation = getVueComponent('Navigation', NavigationNode);
export const Network = getVueComponent('Network', NetworkNode);
export const Octagon = getVueComponent('Octagon', OctagonNode);
export const Package = getVueComponent('Package', PackageNode);
export const Paperclip = getVueComponent('Paperclip', PaperclipNode);
export const PauseCircle = getVueComponent('PauseCircle', PauseCircleNode);
export const Pause = getVueComponent('Pause', PauseNode);
export const PenTool = getVueComponent('PenTool', PenToolNode);
export const Percent = getVueComponent('Percent', PercentNode);
export const PhoneCall = getVueComponent('PhoneCall', PhoneCallNode);
export const PhoneForwarded = getVueComponent('PhoneForwarded', PhoneForwardedNode);
export const PhoneIncoming = getVueComponent('PhoneIncoming', PhoneIncomingNode);
export const PhoneMissed = getVueComponent('PhoneMissed', PhoneMissedNode);
export const PhoneOff = getVueComponent('PhoneOff', PhoneOffNode);
export const PhoneOutgoing = getVueComponent('PhoneOutgoing', PhoneOutgoingNode);
export const Phone = getVueComponent('Phone', PhoneNode);
export const PieChart = getVueComponent('PieChart', PieChartNode);
export const PlayCircle = getVueComponent('PlayCircle', PlayCircleNode);
export const Play = getVueComponent('Play', PlayNode);
export const PlusCircle = getVueComponent('PlusCircle', PlusCircleNode);
export const PlusSquare = getVueComponent('PlusSquare', PlusSquareNode);
export const Plus = getVueComponent('Plus', PlusNode);
export const Pocket = getVueComponent('Pocket', PocketNode);
export const Power = getVueComponent('Power', PowerNode);
export const Printer = getVueComponent('Printer', PrinterNode);
export const Radio = getVueComponent('Radio', RadioNode);
export const RefreshCcw = getVueComponent('RefreshCcw', RefreshCcwNode);
export const RefreshCw = getVueComponent('RefreshCw', RefreshCwNode);
export const Repeat = getVueComponent('Repeat', RepeatNode);
export const Rewind = getVueComponent('Rewind', RewindNode);
export const RotateCcw = getVueComponent('RotateCcw', RotateCcwNode);
export const RotateCw = getVueComponent('RotateCw', RotateCwNode);
export const Rss = getVueComponent('Rss', RssNode);
export const Save = getVueComponent('Save', SaveNode);
export const Scissors = getVueComponent('Scissors', ScissorsNode);
export const ScreenShareOff = getVueComponent('ScreenShareOff', ScreenShareOffNode);
export const ScreenShare = getVueComponent('ScreenShare', ScreenShareNode);
export const Search = getVueComponent('Search', SearchNode);
export const Send = getVueComponent('Send', SendNode);
export const Server = getVueComponent('Server', ServerNode);
export const Settings = getVueComponent('Settings', SettingsNode);
export const Share2 = getVueComponent('Share2', Share2Node);
export const Share = getVueComponent('Share', ShareNode);
export const ShieldOff = getVueComponent('ShieldOff', ShieldOffNode);
export const Shield = getVueComponent('Shield', ShieldNode);
export const ShoppingBag = getVueComponent('ShoppingBag', ShoppingBagNode);
export const ShoppingCart = getVueComponent('ShoppingCart', ShoppingCartNode);
export const Shuffle = getVueComponent('Shuffle', ShuffleNode);
export const Sidebar = getVueComponent('Sidebar', SidebarNode);
export const SkipBack = getVueComponent('SkipBack', SkipBackNode);
export const SkipForward = getVueComponent('SkipForward', SkipForwardNode);
export const Slack = getVueComponent('Slack', SlackNode);
export const Slash = getVueComponent('Slash', SlashNode);
export const Sliders = getVueComponent('Sliders', SlidersNode);
export const Smartphone = getVueComponent('Smartphone', SmartphoneNode);
export const Smile = getVueComponent('Smile', SmileNode);
export const Snowflake = getVueComponent('Snowflake', SnowflakeNode);
export const SortAsc = getVueComponent('SortAsc', SortAscNode);
export const SortDesc = getVueComponent('SortDesc', SortDescNode);
export const Speaker = getVueComponent('Speaker', SpeakerNode);
export const Square = getVueComponent('Square', SquareNode);
export const Star = getVueComponent('Star', StarNode);
export const StopCircle = getVueComponent('StopCircle', StopCircleNode);
export const Strikethrough = getVueComponent('Strikethrough', StrikethroughNode);
export const Sun = getVueComponent('Sun', SunNode);
export const Sunrise = getVueComponent('Sunrise', SunriseNode);
export const Sunset = getVueComponent('Sunset', SunsetNode);
export const SwitchCamera = getVueComponent('SwitchCamera', SwitchCameraNode);
export const Tablet = getVueComponent('Tablet', TabletNode);
export const Tag = getVueComponent('Tag', TagNode);
export const Target = getVueComponent('Target', TargetNode);
export const Terminal = getVueComponent('Terminal', TerminalNode);
export const Thermometer = getVueComponent('Thermometer', ThermometerNode);
export const ThumbsDown = getVueComponent('ThumbsDown', ThumbsDownNode);
export const ThumbsUp = getVueComponent('ThumbsUp', ThumbsUpNode);
export const ToggleLeft = getVueComponent('ToggleLeft', ToggleLeftNode);
export const ToggleRight = getVueComponent('ToggleRight', ToggleRightNode);
export const Tool = getVueComponent('Tool', ToolNode);
export const Trash2 = getVueComponent('Trash2', Trash2Node);
export const Trash = getVueComponent('Trash', TrashNode);
export const Trello = getVueComponent('Trello', TrelloNode);
export const TrendingDown = getVueComponent('TrendingDown', TrendingDownNode);
export const TrendingUp = getVueComponent('TrendingUp', TrendingUpNode);
export const Triangle = getVueComponent('Triangle', TriangleNode);
export const Truck = getVueComponent('Truck', TruckNode);
export const Tv = getVueComponent('Tv', TvNode);
export const Twitch = getVueComponent('Twitch', TwitchNode);
export const Twitter = getVueComponent('Twitter', TwitterNode);
export const Type = getVueComponent('Type', TypeNode);
export const Umbrella = getVueComponent('Umbrella', UmbrellaNode);
export const Underline = getVueComponent('Underline', UnderlineNode);
export const Unlink2 = getVueComponent('Unlink2', Unlink2Node);
export const Unlink = getVueComponent('Unlink', UnlinkNode);
export const Unlock = getVueComponent('Unlock', UnlockNode);
export const UploadCloud = getVueComponent('UploadCloud', UploadCloudNode);
export const Upload = getVueComponent('Upload', UploadNode);
export const UserCheck = getVueComponent('UserCheck', UserCheckNode);
export const UserMinus = getVueComponent('UserMinus', UserMinusNode);
export const UserPlus = getVueComponent('UserPlus', UserPlusNode);
export const UserX = getVueComponent('UserX', UserXNode);
export const User = getVueComponent('User', UserNode);
export const Users = getVueComponent('Users', UsersNode);
export const VideoOff = getVueComponent('VideoOff', VideoOffNode);
export const Video = getVueComponent('Video', VideoNode);
export const Voicemail = getVueComponent('Voicemail', VoicemailNode);
export const Volume1 = getVueComponent('Volume1', Volume1Node);
export const Volume2 = getVueComponent('Volume2', Volume2Node);
export const VolumeX = getVueComponent('VolumeX', VolumeXNode);
export const Volume = getVueComponent('Volume', VolumeNode);
export const Watch = getVueComponent('Watch', WatchNode);
export const WifiOff = getVueComponent('WifiOff', WifiOffNode);
export const Wifi = getVueComponent('Wifi', WifiNode);
export const Wind = getVueComponent('Wind', WindNode);
export const XCircle = getVueComponent('XCircle', XCircleNode);
export const XOctagon = getVueComponent('XOctagon', XOctagonNode);
export const XSquare = getVueComponent('XSquare', XSquareNode);
export const X = getVueComponent('X', XNode);
export const Youtube = getVueComponent('Youtube', YoutubeNode);
export const ZapOff = getVueComponent('ZapOff', ZapOffNode);
export const Zap = getVueComponent('Zap', ZapNode);
export const ZoomIn = getVueComponent('ZoomIn', ZoomInNode);
export const ZoomOut = getVueComponent('ZoomOut', ZoomOutNode);
