name: lucide.dev bug report
description: Help us improve the Lucide site
labels: ['🐛 bug', '🌍 site']
body:
  - type: markdown
    attributes:
      value: |
        Before reporting an issue, please search to see if someone has filed a similar issue before. If there is already an open issue, please add a 👍 and/or leave a comment with additional information.
  - type: checkboxes
    id: browsers
    attributes:
      label: Browser
      description: In which browser(s) are you experiencing the issue? You may select more than one.
      options:
        - label: Chrome/Chromium
        - label: Firefox
        - label: Safari
        - label: Edge
        - label: iOS Safari
        - label: Opera
        - label: Other/not relevant
    validations:
      required: false
  - type: checkboxes
    id: operating-systems
    attributes:
      label: Operating system
      description: In which operating systems are you experiencing the issue? You may select more than one.
      options:
        - label: Windows
        - label: Linux
        - label: macOS
        - label: ChromeOS
        - label: iOS
        - label: Android
        - label: Other/not relevant
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Try to describe in detail the problem you're running into and provide additional context about your working environment if necessary.
      placeholder: e.g. When I do X, Y happens instead of Z
    validations:
      required: true
  - type: textarea
    id: stepsToReproduce
    attributes:
      label: Steps to reproduce
      description: Please provide a detailed guide on how this issue can be reproduced.
      placeholder: |
        1. I click on an icon
        2. I click on `Copy SVG` in the drawer
        3. I paste from the clipboard
        4. A base64 encoded data URI is inserted.
        ...
    validations:
      required: true
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please review the following checklist before submitting your issue.
      options:
        - label: I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)
          required: true
