library lucide_icons;

import "package:flutter/widgets.dart";
import "src/icon_data.dart";

// THIS FILE IS AUTOMATICALLY GENERATED!

class LucideIcons {
  // Icons will be generated here..
  // static const IconData {icon_name} = const LucideIconData({icon_hex});
  // ...
}
