import getReactComponent from './getters/getReactComponent';

import ActivityNode from './icons/activity';
import AirplayNode from './icons/airplay';
import AlertCircleNode from './icons/alert-circle';
import AlertOctagonNode from './icons/alert-octagon';
import AlertTriangleNode from './icons/alert-triangle';
import AlignCenterNode from './icons/align-center';
import AlignJustifyNode from './icons/align-justify';
import AlignLeftNode from './icons/align-left';
import AlignRightNode from './icons/align-right';
import AnchorNode from './icons/anchor';
import ApertureNode from './icons/aperture';
import ArchiveNode from './icons/archive';
import ArrowDownCircleNode from './icons/arrow-down-circle';
import ArrowDownLeftNode from './icons/arrow-down-left';
import ArrowDownRightNode from './icons/arrow-down-right';
import ArrowDownNode from './icons/arrow-down';
import ArrowLeftCircleNode from './icons/arrow-left-circle';
import ArrowLeftNode from './icons/arrow-left';
import ArrowRightCircleNode from './icons/arrow-right-circle';
import ArrowRightNode from './icons/arrow-right';
import ArrowUpCircleNode from './icons/arrow-up-circle';
import ArrowUpLeftNode from './icons/arrow-up-left';
import ArrowUpRightNode from './icons/arrow-up-right';
import ArrowUpNode from './icons/arrow-up';
import AtSignNode from './icons/at-sign';
import AwardNode from './icons/award';
import BarChart2Node from './icons/bar-chart-2';
import BarChartNode from './icons/bar-chart';
import BatteryChargingNode from './icons/battery-charging';
import BatteryFullNode from './icons/battery-full';
import BatteryLowNode from './icons/battery-low';
import BatteryMediumNode from './icons/battery-medium';
import BatteryNode from './icons/battery';
import BellOffNode from './icons/bell-off';
import BellNode from './icons/bell';
import BluetoothNode from './icons/bluetooth';
import BoldNode from './icons/bold';
import BookOpenNode from './icons/book-open';
import BookNode from './icons/book';
import BookmarkNode from './icons/bookmark';
import BoxNode from './icons/box';
import BriefcaseNode from './icons/briefcase';
import CalendarNode from './icons/calendar';
import CameraOffNode from './icons/camera-off';
import CameraNode from './icons/camera';
import CastNode from './icons/cast';
import CheckCircleNode from './icons/check-circle';
import CheckSquareNode from './icons/check-square';
import CheckNode from './icons/check';
import ChevronDownNode from './icons/chevron-down';
import ChevronLeftNode from './icons/chevron-left';
import ChevronRightNode from './icons/chevron-right';
import ChevronUpNode from './icons/chevron-up';
import ChevronsDownNode from './icons/chevrons-down';
import ChevronsLeftNode from './icons/chevrons-left';
import ChevronsRightNode from './icons/chevrons-right';
import ChevronsUpNode from './icons/chevrons-up';
import ChromeNode from './icons/chrome';
import CircleNode from './icons/circle';
import ClipboardNode from './icons/clipboard';
import ClockNode from './icons/clock';
import CloudDrizzleNode from './icons/cloud-drizzle';
import CloudLightningNode from './icons/cloud-lightning';
import CloudOffNode from './icons/cloud-off';
import CloudRainNode from './icons/cloud-rain';
import CloudSnowNode from './icons/cloud-snow';
import CloudNode from './icons/cloud';
import CodeNode from './icons/code';
import CodepenNode from './icons/codepen';
import CodesandboxNode from './icons/codesandbox';
import CoffeeNode from './icons/coffee';
import ColumnsNode from './icons/columns';
import CommandNode from './icons/command';
import CompassNode from './icons/compass';
import ContactNode from './icons/contact';
import ContrastNode from './icons/contrast';
import CopyNode from './icons/copy';
import CopyleftNode from './icons/copyleft';
import CopyrightNode from './icons/copyright';
import CornerDownLeftNode from './icons/corner-down-left';
import CornerDownRightNode from './icons/corner-down-right';
import CornerLeftDownNode from './icons/corner-left-down';
import CornerLeftUpNode from './icons/corner-left-up';
import CornerRightDownNode from './icons/corner-right-down';
import CornerRightUpNode from './icons/corner-right-up';
import CornerUpLeftNode from './icons/corner-up-left';
import CornerUpRightNode from './icons/corner-up-right';
import CpuNode from './icons/cpu';
import CreditCardNode from './icons/credit-card';
import CropNode from './icons/crop';
import CrosshairNode from './icons/crosshair';
import DatabaseNode from './icons/database';
import DeleteNode from './icons/delete';
import DiscNode from './icons/disc';
import DivideCircleNode from './icons/divide-circle';
import DivideSquareNode from './icons/divide-square';
import DivideNode from './icons/divide';
import DollarSignNode from './icons/dollar-sign';
import DownloadCloudNode from './icons/download-cloud';
import DownloadNode from './icons/download';
import DribbbleNode from './icons/dribbble';
import DropletNode from './icons/droplet';
import Edit2Node from './icons/edit-2';
import Edit3Node from './icons/edit-3';
import EditNode from './icons/edit';
import ExternalLinkNode from './icons/external-link';
import EyeOffNode from './icons/eye-off';
import EyeNode from './icons/eye';
import FacebookNode from './icons/facebook';
import FastForwardNode from './icons/fast-forward';
import FeatherNode from './icons/feather';
import FigmaNode from './icons/figma';
import FileMinusNode from './icons/file-minus';
import FilePlusNode from './icons/file-plus';
import FileTextNode from './icons/file-text';
import FileNode from './icons/file';
import FilmNode from './icons/film';
import FilterNode from './icons/filter';
import FlagNode from './icons/flag';
import FolderMinusNode from './icons/folder-minus';
import FolderPlusNode from './icons/folder-plus';
import FolderNode from './icons/folder';
import FramerNode from './icons/framer';
import FrownNode from './icons/frown';
import Gamepad2Node from './icons/gamepad-2';
import GamepadNode from './icons/gamepad';
import GiftNode from './icons/gift';
import GitBranchNode from './icons/git-branch';
import GitCommitNode from './icons/git-commit';
import GitMergeNode from './icons/git-merge';
import GitPullRequestNode from './icons/git-pull-request';
import GitHubNode from './icons/github';
import GitlabNode from './icons/gitlab';
import GlobeNode from './icons/globe';
import GridNode from './icons/grid';
import GripHorizontalNode from './icons/grip-horizontal';
import GripVerticalNode from './icons/grip-vertical';
import HardDriveNode from './icons/hard-drive';
import HashNode from './icons/hash';
import HeadphonesNode from './icons/headphones';
import HeartNode from './icons/heart';
import HelpCircleNode from './icons/help-circle';
import HexagonNode from './icons/hexagon';
import HighlighterNode from './icons/highlighter';
import HomeNode from './icons/home';
import ImageNode from './icons/image';
import InboxNode from './icons/inbox';
import InfoNode from './icons/info';
import InstagramNode from './icons/instagram';
import ItalicNode from './icons/italic';
import KeyNode from './icons/key';
import LanguagesNode from './icons/languages';
import LayersNode from './icons/layers';
import LayoutNode from './icons/layout';
import LifeBuoyNode from './icons/life-buoy';
import Link2OffNode from './icons/link-2-off';
import Link2Node from './icons/link-2';
import LinkNode from './icons/link';
import LinkedinNode from './icons/linkedin';
import ListNode from './icons/list';
import LoaderNode from './icons/loader';
import LockNode from './icons/lock';
import LogInNode from './icons/log-in';
import LogOutNode from './icons/log-out';
import MailNode from './icons/mail';
import MapPinNode from './icons/map-pin';
import MapNode from './icons/map';
import Maximize2Node from './icons/maximize-2';
import MaximizeNode from './icons/maximize';
import MehNode from './icons/meh';
import MenuNode from './icons/menu';
import MessageCircleNode from './icons/message-circle';
import MessageSquareNode from './icons/message-square';
import MicOffNode from './icons/mic-off';
import MicNode from './icons/mic';
import Minimize2Node from './icons/minimize-2';
import MinimizeNode from './icons/minimize';
import MinusCircleNode from './icons/minus-circle';
import MinusSquareNode from './icons/minus-square';
import MinusNode from './icons/minus';
import MonitorNode from './icons/monitor';
import MoonNode from './icons/moon';
import MoreHorizontalNode from './icons/more-horizontal';
import MoreVerticalNode from './icons/more-vertical';
import MousePointerNode from './icons/mouse-pointer';
import MoveNode from './icons/move';
import MusicNode from './icons/music';
import Navigation2Node from './icons/navigation-2';
import NavigationNode from './icons/navigation';
import NetworkNode from './icons/network';
import OctagonNode from './icons/octagon';
import PackageNode from './icons/package';
import PaperclipNode from './icons/paperclip';
import PauseCircleNode from './icons/pause-circle';
import PauseNode from './icons/pause';
import PenToolNode from './icons/pen-tool';
import PercentNode from './icons/percent';
import PhoneCallNode from './icons/phone-call';
import PhoneForwardedNode from './icons/phone-forwarded';
import PhoneIncomingNode from './icons/phone-incoming';
import PhoneMissedNode from './icons/phone-missed';
import PhoneOffNode from './icons/phone-off';
import PhoneOutgoingNode from './icons/phone-outgoing';
import PhoneNode from './icons/phone';
import PieChartNode from './icons/pie-chart';
import PlayCircleNode from './icons/play-circle';
import PlayNode from './icons/play';
import PlusCircleNode from './icons/plus-circle';
import PlusSquareNode from './icons/plus-square';
import PlusNode from './icons/plus';
import PocketNode from './icons/pocket';
import PowerNode from './icons/power';
import PrinterNode from './icons/printer';
import RadioNode from './icons/radio';
import RefreshCcwNode from './icons/refresh-ccw';
import RefreshCwNode from './icons/refresh-cw';
import RepeatNode from './icons/repeat';
import RewindNode from './icons/rewind';
import RotateCcwNode from './icons/rotate-ccw';
import RotateCwNode from './icons/rotate-cw';
import RssNode from './icons/rss';
import SaveNode from './icons/save';
import ScissorsNode from './icons/scissors';
import ScreenShareOffNode from './icons/screen-share-off';
import ScreenShareNode from './icons/screen-share';
import SearchNode from './icons/search';
import SendNode from './icons/send';
import ServerNode from './icons/server';
import SettingsNode from './icons/settings';
import Share2Node from './icons/share-2';
import ShareNode from './icons/share';
import ShieldOffNode from './icons/shield-off';
import ShieldNode from './icons/shield';
import ShoppingBagNode from './icons/shopping-bag';
import ShoppingCartNode from './icons/shopping-cart';
import ShuffleNode from './icons/shuffle';
import SidebarNode from './icons/sidebar';
import SkipBackNode from './icons/skip-back';
import SkipForwardNode from './icons/skip-forward';
import SlackNode from './icons/slack';
import SlashNode from './icons/slash';
import SlidersNode from './icons/sliders';
import SmartphoneNode from './icons/smartphone';
import SmileNode from './icons/smile';
import SnowflakeNode from './icons/snowflake';
import SortAscNode from './icons/sort-asc';
import SortDescNode from './icons/sort-desc';
import SpeakerNode from './icons/speaker';
import SquareNode from './icons/square';
import StarNode from './icons/star';
import StopCircleNode from './icons/stop-circle';
import StrikethroughNode from './icons/strikethrough';
import SunNode from './icons/sun';
import SunriseNode from './icons/sunrise';
import SunsetNode from './icons/sunset';
import SwitchCameraNode from './icons/switch-camera';
import TabletNode from './icons/tablet';
import TagNode from './icons/tag';
import TargetNode from './icons/target';
import TerminalNode from './icons/terminal';
import ThermometerNode from './icons/thermometer';
import ThumbsDownNode from './icons/thumbs-down';
import ThumbsUpNode from './icons/thumbs-up';
import ToggleLeftNode from './icons/toggle-left';
import ToggleRightNode from './icons/toggle-right';
import ToolNode from './icons/tool';
import Trash2Node from './icons/trash-2';
import TrashNode from './icons/trash';
import TrelloNode from './icons/trello';
import TrendingDownNode from './icons/trending-down';
import TrendingUpNode from './icons/trending-up';
import TriangleNode from './icons/triangle';
import TruckNode from './icons/truck';
import TvNode from './icons/tv';
import TwitchNode from './icons/twitch';
import TwitterNode from './icons/twitter';
import TypeNode from './icons/type';
import UmbrellaNode from './icons/umbrella';
import UnderlineNode from './icons/underline';
import Unlink2Node from './icons/unlink-2';
import UnlinkNode from './icons/unlink';
import UnlockNode from './icons/unlock';
import UploadCloudNode from './icons/upload-cloud';
import UploadNode from './icons/upload';
import UserCheckNode from './icons/user-check';
import UserMinusNode from './icons/user-minus';
import UserPlusNode from './icons/user-plus';
import UserXNode from './icons/user-x';
import UserNode from './icons/user';
import UsersNode from './icons/users';
import VideoOffNode from './icons/video-off';
import VideoNode from './icons/video';
import VoicemailNode from './icons/voicemail';
import Volume1Node from './icons/volume-1';
import Volume2Node from './icons/volume-2';
import VolumeXNode from './icons/volume-x';
import VolumeNode from './icons/volume';
import WatchNode from './icons/watch';
import WifiOffNode from './icons/wifi-off';
import WifiNode from './icons/wifi';
import WindNode from './icons/wind';
import XCircleNode from './icons/x-circle';
import XOctagonNode from './icons/x-octagon';
import XSquareNode from './icons/x-square';
import XNode from './icons/x';
import YoutubeNode from './icons/youtube';
import ZapOffNode from './icons/zap-off';
import ZapNode from './icons/zap';
import ZoomInNode from './icons/zoom-in';
import ZoomOutNode from './icons/zoom-out';

export const Activity = getReactComponent('Activity', ActivityNode);
export const Airplay = getReactComponent('Airplay', AirplayNode);
export const AlertCircle = getReactComponent('AlertCircle', AlertCircleNode);
export const AlertOctagon = getReactComponent('AlertOctagon', AlertOctagonNode);
export const AlertTriangle = getReactComponent('AlertTriangle', AlertTriangleNode);
export const AlignCenter = getReactComponent('AlignCenter', AlignCenterNode);
export const AlignJustify = getReactComponent('AlignJustify', AlignJustifyNode);
export const AlignLeft = getReactComponent('AlignLeft', AlignLeftNode);
export const AlignRight = getReactComponent('AlignRight', AlignRightNode);
export const Anchor = getReactComponent('Anchor', AnchorNode);
export const Aperture = getReactComponent('Aperture', ApertureNode);
export const Archive = getReactComponent('Archive', ArchiveNode);
export const ArrowDownCircle = getReactComponent('ArrowDownCircle', ArrowDownCircleNode);
export const ArrowDownLeft = getReactComponent('ArrowDownLeft', ArrowDownLeftNode);
export const ArrowDownRight = getReactComponent('ArrowDownRight', ArrowDownRightNode);
export const ArrowDown = getReactComponent('ArrowDown', ArrowDownNode);
export const ArrowLeftCircle = getReactComponent('ArrowLeftCircle', ArrowLeftCircleNode);
export const ArrowLeft = getReactComponent('ArrowLeft', ArrowLeftNode);
export const ArrowRightCircle = getReactComponent('ArrowRightCircle', ArrowRightCircleNode);
export const ArrowRight = getReactComponent('ArrowRight', ArrowRightNode);
export const ArrowUpCircle = getReactComponent('ArrowUpCircle', ArrowUpCircleNode);
export const ArrowUpLeft = getReactComponent('ArrowUpLeft', ArrowUpLeftNode);
export const ArrowUpRight = getReactComponent('ArrowUpRight', ArrowUpRightNode);
export const ArrowUp = getReactComponent('ArrowUp', ArrowUpNode);
export const AtSign = getReactComponent('AtSign', AtSignNode);
export const Award = getReactComponent('Award', AwardNode);
export const BarChart2 = getReactComponent('BarChart2', BarChart2Node);
export const BarChart = getReactComponent('BarChart', BarChartNode);
export const BatteryCharging = getReactComponent('BatteryCharging', BatteryChargingNode);
export const BatteryFull = getReactComponent('BatteryFull', BatteryFullNode);
export const BatteryLow = getReactComponent('BatteryLow', BatteryLowNode);
export const BatteryMedium = getReactComponent('BatteryMedium', BatteryMediumNode);
export const Battery = getReactComponent('Battery', BatteryNode);
export const BellOff = getReactComponent('BellOff', BellOffNode);
export const Bell = getReactComponent('Bell', BellNode);
export const Bluetooth = getReactComponent('Bluetooth', BluetoothNode);
export const Bold = getReactComponent('Bold', BoldNode);
export const BookOpen = getReactComponent('BookOpen', BookOpenNode);
export const Book = getReactComponent('Book', BookNode);
export const Bookmark = getReactComponent('Bookmark', BookmarkNode);
export const Box = getReactComponent('Box', BoxNode);
export const Briefcase = getReactComponent('Briefcase', BriefcaseNode);
export const Calendar = getReactComponent('Calendar', CalendarNode);
export const CameraOff = getReactComponent('CameraOff', CameraOffNode);
export const Camera = getReactComponent('Camera', CameraNode);
export const Cast = getReactComponent('Cast', CastNode);
export const CheckCircle = getReactComponent('CheckCircle', CheckCircleNode);
export const CheckSquare = getReactComponent('CheckSquare', CheckSquareNode);
export const Check = getReactComponent('Check', CheckNode);
export const ChevronDown = getReactComponent('ChevronDown', ChevronDownNode);
export const ChevronLeft = getReactComponent('ChevronLeft', ChevronLeftNode);
export const ChevronRight = getReactComponent('ChevronRight', ChevronRightNode);
export const ChevronUp = getReactComponent('ChevronUp', ChevronUpNode);
export const ChevronsDown = getReactComponent('ChevronsDown', ChevronsDownNode);
export const ChevronsLeft = getReactComponent('ChevronsLeft', ChevronsLeftNode);
export const ChevronsRight = getReactComponent('ChevronsRight', ChevronsRightNode);
export const ChevronsUp = getReactComponent('ChevronsUp', ChevronsUpNode);
export const Chrome = getReactComponent('Chrome', ChromeNode);
export const Circle = getReactComponent('Circle', CircleNode);
export const Clipboard = getReactComponent('Clipboard', ClipboardNode);
export const Clock = getReactComponent('Clock', ClockNode);
export const CloudDrizzle = getReactComponent('CloudDrizzle', CloudDrizzleNode);
export const CloudLightning = getReactComponent('CloudLightning', CloudLightningNode);
export const CloudOff = getReactComponent('CloudOff', CloudOffNode);
export const CloudRain = getReactComponent('CloudRain', CloudRainNode);
export const CloudSnow = getReactComponent('CloudSnow', CloudSnowNode);
export const Cloud = getReactComponent('Cloud', CloudNode);
export const Code = getReactComponent('Code', CodeNode);
export const Codepen = getReactComponent('Codepen', CodepenNode);
export const Codesandbox = getReactComponent('Codesandbox', CodesandboxNode);
export const Coffee = getReactComponent('Coffee', CoffeeNode);
export const Columns = getReactComponent('Columns', ColumnsNode);
export const Command = getReactComponent('Command', CommandNode);
export const Compass = getReactComponent('Compass', CompassNode);
export const Contact = getReactComponent('Contact', ContactNode);
export const Contrast = getReactComponent('Contrast', ContrastNode);
export const Copy = getReactComponent('Copy', CopyNode);
export const Copyleft = getReactComponent('Copyleft', CopyleftNode);
export const Copyright = getReactComponent('Copyright', CopyrightNode);
export const CornerDownLeft = getReactComponent('CornerDownLeft', CornerDownLeftNode);
export const CornerDownRight = getReactComponent('CornerDownRight', CornerDownRightNode);
export const CornerLeftDown = getReactComponent('CornerLeftDown', CornerLeftDownNode);
export const CornerLeftUp = getReactComponent('CornerLeftUp', CornerLeftUpNode);
export const CornerRightDown = getReactComponent('CornerRightDown', CornerRightDownNode);
export const CornerRightUp = getReactComponent('CornerRightUp', CornerRightUpNode);
export const CornerUpLeft = getReactComponent('CornerUpLeft', CornerUpLeftNode);
export const CornerUpRight = getReactComponent('CornerUpRight', CornerUpRightNode);
export const Cpu = getReactComponent('Cpu', CpuNode);
export const CreditCard = getReactComponent('CreditCard', CreditCardNode);
export const Crop = getReactComponent('Crop', CropNode);
export const Crosshair = getReactComponent('Crosshair', CrosshairNode);
export const Database = getReactComponent('Database', DatabaseNode);
export const Delete = getReactComponent('Delete', DeleteNode);
export const Disc = getReactComponent('Disc', DiscNode);
export const DivideCircle = getReactComponent('DivideCircle', DivideCircleNode);
export const DivideSquare = getReactComponent('DivideSquare', DivideSquareNode);
export const Divide = getReactComponent('Divide', DivideNode);
export const DollarSign = getReactComponent('DollarSign', DollarSignNode);
export const DownloadCloud = getReactComponent('DownloadCloud', DownloadCloudNode);
export const Download = getReactComponent('Download', DownloadNode);
export const Dribbble = getReactComponent('Dribbble', DribbbleNode);
export const Droplet = getReactComponent('Droplet', DropletNode);
export const Edit2 = getReactComponent('Edit2', Edit2Node);
export const Edit3 = getReactComponent('Edit3', Edit3Node);
export const Edit = getReactComponent('Edit', EditNode);
export const ExternalLink = getReactComponent('ExternalLink', ExternalLinkNode);
export const EyeOff = getReactComponent('EyeOff', EyeOffNode);
export const Eye = getReactComponent('Eye', EyeNode);
export const Facebook = getReactComponent('Facebook', FacebookNode);
export const FastForward = getReactComponent('FastForward', FastForwardNode);
export const Feather = getReactComponent('Feather', FeatherNode);
export const Figma = getReactComponent('Figma', FigmaNode);
export const FileMinus = getReactComponent('FileMinus', FileMinusNode);
export const FilePlus = getReactComponent('FilePlus', FilePlusNode);
export const FileText = getReactComponent('FileText', FileTextNode);
export const File = getReactComponent('File', FileNode);
export const Film = getReactComponent('Film', FilmNode);
export const Filter = getReactComponent('Filter', FilterNode);
export const Flag = getReactComponent('Flag', FlagNode);
export const FolderMinus = getReactComponent('FolderMinus', FolderMinusNode);
export const FolderPlus = getReactComponent('FolderPlus', FolderPlusNode);
export const Folder = getReactComponent('Folder', FolderNode);
export const Framer = getReactComponent('Framer', FramerNode);
export const Frown = getReactComponent('Frown', FrownNode);
export const Gamepad2 = getReactComponent('Gamepad2', Gamepad2Node);
export const Gamepad = getReactComponent('Gamepad', GamepadNode);
export const Gift = getReactComponent('Gift', GiftNode);
export const GitBranch = getReactComponent('GitBranch', GitBranchNode);
export const GitCommit = getReactComponent('GitCommit', GitCommitNode);
export const GitMerge = getReactComponent('GitMerge', GitMergeNode);
export const GitPullRequest = getReactComponent('GitPullRequest', GitPullRequestNode);
export const GitHub = getReactComponent('GitHub', GitHubNode);
export const Gitlab = getReactComponent('Gitlab', GitlabNode);
export const Globe = getReactComponent('Globe', GlobeNode);
export const Grid = getReactComponent('Grid', GridNode);
export const GripHorizontal = getReactComponent('GripHorizontal', GripHorizontalNode);
export const GripVertical = getReactComponent('GripVertical', GripVerticalNode);
export const HardDrive = getReactComponent('HardDrive', HardDriveNode);
export const Hash = getReactComponent('Hash', HashNode);
export const Headphones = getReactComponent('Headphones', HeadphonesNode);
export const Heart = getReactComponent('Heart', HeartNode);
export const HelpCircle = getReactComponent('HelpCircle', HelpCircleNode);
export const Hexagon = getReactComponent('Hexagon', HexagonNode);
export const Highlighter = getReactComponent('Highlighter', HighlighterNode);
export const Home = getReactComponent('Home', HomeNode);
export const Image = getReactComponent('Image', ImageNode);
export const Inbox = getReactComponent('Inbox', InboxNode);
export const Info = getReactComponent('Info', InfoNode);
export const Instagram = getReactComponent('Instagram', InstagramNode);
export const Italic = getReactComponent('Italic', ItalicNode);
export const Key = getReactComponent('Key', KeyNode);
export const Languages = getReactComponent('Languages', LanguagesNode);
export const Layers = getReactComponent('Layers', LayersNode);
export const Layout = getReactComponent('Layout', LayoutNode);
export const LifeBuoy = getReactComponent('LifeBuoy', LifeBuoyNode);
export const Link2Off = getReactComponent('Link2Off', Link2OffNode);
export const Link2 = getReactComponent('Link2', Link2Node);
export const Link = getReactComponent('Link', LinkNode);
export const Linkedin = getReactComponent('Linkedin', LinkedinNode);
export const List = getReactComponent('List', ListNode);
export const Loader = getReactComponent('Loader', LoaderNode);
export const Lock = getReactComponent('Lock', LockNode);
export const LogIn = getReactComponent('LogIn', LogInNode);
export const LogOut = getReactComponent('LogOut', LogOutNode);
export const Mail = getReactComponent('Mail', MailNode);
export const MapPin = getReactComponent('MapPin', MapPinNode);
export const Map = getReactComponent('Map', MapNode);
export const Maximize2 = getReactComponent('Maximize2', Maximize2Node);
export const Maximize = getReactComponent('Maximize', MaximizeNode);
export const Meh = getReactComponent('Meh', MehNode);
export const Menu = getReactComponent('Menu', MenuNode);
export const MessageCircle = getReactComponent('MessageCircle', MessageCircleNode);
export const MessageSquare = getReactComponent('MessageSquare', MessageSquareNode);
export const MicOff = getReactComponent('MicOff', MicOffNode);
export const Mic = getReactComponent('Mic', MicNode);
export const Minimize2 = getReactComponent('Minimize2', Minimize2Node);
export const Minimize = getReactComponent('Minimize', MinimizeNode);
export const MinusCircle = getReactComponent('MinusCircle', MinusCircleNode);
export const MinusSquare = getReactComponent('MinusSquare', MinusSquareNode);
export const Minus = getReactComponent('Minus', MinusNode);
export const Monitor = getReactComponent('Monitor', MonitorNode);
export const Moon = getReactComponent('Moon', MoonNode);
export const MoreHorizontal = getReactComponent('MoreHorizontal', MoreHorizontalNode);
export const MoreVertical = getReactComponent('MoreVertical', MoreVerticalNode);
export const MousePointer = getReactComponent('MousePointer', MousePointerNode);
export const Move = getReactComponent('Move', MoveNode);
export const Music = getReactComponent('Music', MusicNode);
export const Navigation2 = getReactComponent('Navigation2', Navigation2Node);
export const Navigation = getReactComponent('Navigation', NavigationNode);
export const Network = getReactComponent('Network', NetworkNode);
export const Octagon = getReactComponent('Octagon', OctagonNode);
export const Package = getReactComponent('Package', PackageNode);
export const Paperclip = getReactComponent('Paperclip', PaperclipNode);
export const PauseCircle = getReactComponent('PauseCircle', PauseCircleNode);
export const Pause = getReactComponent('Pause', PauseNode);
export const PenTool = getReactComponent('PenTool', PenToolNode);
export const Percent = getReactComponent('Percent', PercentNode);
export const PhoneCall = getReactComponent('PhoneCall', PhoneCallNode);
export const PhoneForwarded = getReactComponent('PhoneForwarded', PhoneForwardedNode);
export const PhoneIncoming = getReactComponent('PhoneIncoming', PhoneIncomingNode);
export const PhoneMissed = getReactComponent('PhoneMissed', PhoneMissedNode);
export const PhoneOff = getReactComponent('PhoneOff', PhoneOffNode);
export const PhoneOutgoing = getReactComponent('PhoneOutgoing', PhoneOutgoingNode);
export const Phone = getReactComponent('Phone', PhoneNode);
export const PieChart = getReactComponent('PieChart', PieChartNode);
export const PlayCircle = getReactComponent('PlayCircle', PlayCircleNode);
export const Play = getReactComponent('Play', PlayNode);
export const PlusCircle = getReactComponent('PlusCircle', PlusCircleNode);
export const PlusSquare = getReactComponent('PlusSquare', PlusSquareNode);
export const Plus = getReactComponent('Plus', PlusNode);
export const Pocket = getReactComponent('Pocket', PocketNode);
export const Power = getReactComponent('Power', PowerNode);
export const Printer = getReactComponent('Printer', PrinterNode);
export const Radio = getReactComponent('Radio', RadioNode);
export const RefreshCcw = getReactComponent('RefreshCcw', RefreshCcwNode);
export const RefreshCw = getReactComponent('RefreshCw', RefreshCwNode);
export const Repeat = getReactComponent('Repeat', RepeatNode);
export const Rewind = getReactComponent('Rewind', RewindNode);
export const RotateCcw = getReactComponent('RotateCcw', RotateCcwNode);
export const RotateCw = getReactComponent('RotateCw', RotateCwNode);
export const Rss = getReactComponent('Rss', RssNode);
export const Save = getReactComponent('Save', SaveNode);
export const Scissors = getReactComponent('Scissors', ScissorsNode);
export const ScreenShareOff = getReactComponent('ScreenShareOff', ScreenShareOffNode);
export const ScreenShare = getReactComponent('ScreenShare', ScreenShareNode);
export const Search = getReactComponent('Search', SearchNode);
export const Send = getReactComponent('Send', SendNode);
export const Server = getReactComponent('Server', ServerNode);
export const Settings = getReactComponent('Settings', SettingsNode);
export const Share2 = getReactComponent('Share2', Share2Node);
export const Share = getReactComponent('Share', ShareNode);
export const ShieldOff = getReactComponent('ShieldOff', ShieldOffNode);
export const Shield = getReactComponent('Shield', ShieldNode);
export const ShoppingBag = getReactComponent('ShoppingBag', ShoppingBagNode);
export const ShoppingCart = getReactComponent('ShoppingCart', ShoppingCartNode);
export const Shuffle = getReactComponent('Shuffle', ShuffleNode);
export const Sidebar = getReactComponent('Sidebar', SidebarNode);
export const SkipBack = getReactComponent('SkipBack', SkipBackNode);
export const SkipForward = getReactComponent('SkipForward', SkipForwardNode);
export const Slack = getReactComponent('Slack', SlackNode);
export const Slash = getReactComponent('Slash', SlashNode);
export const Sliders = getReactComponent('Sliders', SlidersNode);
export const Smartphone = getReactComponent('Smartphone', SmartphoneNode);
export const Smile = getReactComponent('Smile', SmileNode);
export const Snowflake = getReactComponent('Snowflake', SnowflakeNode);
export const SortAsc = getReactComponent('SortAsc', SortAscNode);
export const SortDesc = getReactComponent('SortDesc', SortDescNode);
export const Speaker = getReactComponent('Speaker', SpeakerNode);
export const Square = getReactComponent('Square', SquareNode);
export const Star = getReactComponent('Star', StarNode);
export const StopCircle = getReactComponent('StopCircle', StopCircleNode);
export const Strikethrough = getReactComponent('Strikethrough', StrikethroughNode);
export const Sun = getReactComponent('Sun', SunNode);
export const Sunrise = getReactComponent('Sunrise', SunriseNode);
export const Sunset = getReactComponent('Sunset', SunsetNode);
export const SwitchCamera = getReactComponent('SwitchCamera', SwitchCameraNode);
export const Tablet = getReactComponent('Tablet', TabletNode);
export const Tag = getReactComponent('Tag', TagNode);
export const Target = getReactComponent('Target', TargetNode);
export const Terminal = getReactComponent('Terminal', TerminalNode);
export const Thermometer = getReactComponent('Thermometer', ThermometerNode);
export const ThumbsDown = getReactComponent('ThumbsDown', ThumbsDownNode);
export const ThumbsUp = getReactComponent('ThumbsUp', ThumbsUpNode);
export const ToggleLeft = getReactComponent('ToggleLeft', ToggleLeftNode);
export const ToggleRight = getReactComponent('ToggleRight', ToggleRightNode);
export const Tool = getReactComponent('Tool', ToolNode);
export const Trash2 = getReactComponent('Trash2', Trash2Node);
export const Trash = getReactComponent('Trash', TrashNode);
export const Trello = getReactComponent('Trello', TrelloNode);
export const TrendingDown = getReactComponent('TrendingDown', TrendingDownNode);
export const TrendingUp = getReactComponent('TrendingUp', TrendingUpNode);
export const Triangle = getReactComponent('Triangle', TriangleNode);
export const Truck = getReactComponent('Truck', TruckNode);
export const Tv = getReactComponent('Tv', TvNode);
export const Twitch = getReactComponent('Twitch', TwitchNode);
export const Twitter = getReactComponent('Twitter', TwitterNode);
export const Type = getReactComponent('Type', TypeNode);
export const Umbrella = getReactComponent('Umbrella', UmbrellaNode);
export const Underline = getReactComponent('Underline', UnderlineNode);
export const Unlink2 = getReactComponent('Unlink2', Unlink2Node);
export const Unlink = getReactComponent('Unlink', UnlinkNode);
export const Unlock = getReactComponent('Unlock', UnlockNode);
export const UploadCloud = getReactComponent('UploadCloud', UploadCloudNode);
export const Upload = getReactComponent('Upload', UploadNode);
export const UserCheck = getReactComponent('UserCheck', UserCheckNode);
export const UserMinus = getReactComponent('UserMinus', UserMinusNode);
export const UserPlus = getReactComponent('UserPlus', UserPlusNode);
export const UserX = getReactComponent('UserX', UserXNode);
export const User = getReactComponent('User', UserNode);
export const Users = getReactComponent('Users', UsersNode);
export const VideoOff = getReactComponent('VideoOff', VideoOffNode);
export const Video = getReactComponent('Video', VideoNode);
export const Voicemail = getReactComponent('Voicemail', VoicemailNode);
export const Volume1 = getReactComponent('Volume1', Volume1Node);
export const Volume2 = getReactComponent('Volume2', Volume2Node);
export const VolumeX = getReactComponent('VolumeX', VolumeXNode);
export const Volume = getReactComponent('Volume', VolumeNode);
export const Watch = getReactComponent('Watch', WatchNode);
export const WifiOff = getReactComponent('WifiOff', WifiOffNode);
export const Wifi = getReactComponent('Wifi', WifiNode);
export const Wind = getReactComponent('Wind', WindNode);
export const XCircle = getReactComponent('XCircle', XCircleNode);
export const XOctagon = getReactComponent('XOctagon', XOctagonNode);
export const XSquare = getReactComponent('XSquare', XSquareNode);
export const X = getReactComponent('X', XNode);
export const Youtube = getReactComponent('Youtube', YoutubeNode);
export const ZapOff = getReactComponent('ZapOff', ZapOffNode);
export const Zap = getReactComponent('Zap', ZapNode);
export const ZoomIn = getReactComponent('ZoomIn', ZoomInNode);
export const ZoomOut = getReactComponent('ZoomOut', ZoomOutNode);
