import { parseHTML } from 'linkedom';
import { getQueriesForElement } from '@testing-library/dom';
import { experimental_AstroContainer as AstroContainer } from 'astro/container';
import { type AstroComponentFactory, HTMLString } from 'astro/runtime/server/index.js';
import type { RenderFn } from './types';

const ASTRO_DEBUGGING_ATTRIBUTE = 'data-astro-source';

export const render = async function (AstroComponent, options?) {
  const astroContainer = await AstroContainer.create();
  const htmlString = await astroContainer.renderToString(
    AstroComponent as AstroComponentFactory,
    options,
  );

  const { document } = parseHTML(injectMissingParentTags(htmlString));
  const container = document.body;

  // firstElementChild is the svg and we know it exists
  removeIrrelevantAttributes(container.firstElementChild!);

  return { container, html: htmlString, ...getQueriesForElement(container) };
} satisfies RenderFn;

// html strings need to be marked with this class
// otherwise, Astro is gonna escape the the html entities
export function createAstroHTMLString(htmlString: string) {
  return new HTMLString(htmlString);
}

// needed so linkedom generates the tree correctly
function injectMissingParentTags(markup: string) {
  return `<html><body>${markup}</body></html>`;
}

// remove irrelevant metadata generated by the astro dev container
// that could cause snapshots to be nondeterministic
function removeIrrelevantAttributes(element: Element) {
  for (let attribute of element.attributes!) {
    if (attribute.name.startsWith(ASTRO_DEBUGGING_ATTRIBUTE)) {
      element.removeAttribute(attribute.name);
    }
  }
}
