name: Icon preview comment

on:
  workflow_run:
    workflows: ['Pull request icon preview']
    types:
      - completed

permissions:
  contents: read
  # Download the pr_number artifact from the triggering run.
  actions: read
  # Create or update the icon preview comment on the PR.
  issues: write
  pull-requests: write

jobs:
  upload:
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success'
    steps:
      - name: 'Download artifact'
        uses: actions/github-script@f28e40c7f34bde8b3046d885e986cb6290c5673b # v7.1.0
        with:
          script: |
            let allArtifacts = await github.rest.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: context.payload.workflow_run.id,
            });
            let matchArtifact = allArtifacts.data.artifacts.filter((artifact) => {
              return artifact.name == "pr_number"
            })[0];
            let download = await github.rest.actions.downloadArtifact({
               owner: context.repo.owner,
               repo: context.repo.repo,
               artifact_id: matchArtifact.id,
               archive_format: 'zip',
            });
            const fs = require('fs');
            fs.writeFileSync('${{github.workspace}}/pr_number.zip', Buffer.from(download.data));

      - name: 'Unzip artifact'
        run: unzip pr_number.zip

      - name: 'Get PR number'
        run: echo "number=$(cat NR)" >> $GITHUB_OUTPUT
        id: pr-number

      - name: Find Comment
        uses: peter-evans/find-comment@a54c31d7fa095754bfef525c0c8e5e5674c4b4b1 # v2.4.0
        id: pr-comment
        with:
          issue-number: ${{ steps.pr-number.outputs.number }}
          comment-author: 'github-actions[bot]'
          body-includes: Added or changed icons

      - name: Create or update comment
        uses: peter-evans/create-or-update-comment@23ff15729ef2fc348714a3bb66d2f655ca9066f2 # v3.1.0
        with:
          comment-id: ${{ steps.pr-comment.outputs.comment-id }}
          issue-number: ${{ steps.pr-number.outputs.number }}
          body-path: comment-markup.md
          edit-mode: replace
