name: 'Pull Request Labeler'
on:
  - pull_request_target

permissions:
  contents: read

jobs:
  triage:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/labeler@v5
