name: Test Lucide Svelte

on:
  pull_request:
    paths:
      - packages/lucide/**
  push:
    paths:
      - packages/lucide/**

jobs:
  lucide:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3.4.1
        with:
          node-version: 16
          cache: 'pnpm'

      - name: Install pnpm
        uses: pnpm/action-setup@v2.0.1

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm --filter lucide build

      - name: Test
        run: pnpm --filter lucide test

