name: Lucide Vue checks

on:
  pull_request:
    paths:
      - packages/lucide-vue/**
      - tools/build-icons/**
      - pnpm-lock.yaml

jobs:
  lucide-vue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3.8.1
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm --filter lucide-vue build

      - name: Test
        run: pnpm --filter lucide-vue test
