name: Lucide font checks

on:
  push:
    branches:
      - next
  pull_request:
    paths:
      - tools/build-font/**
      - pnpm-lock.yaml

permissions:
  contents: read

jobs:
  lucide-font:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          cache: 'pnpm'
          node-version-file: 'package.json'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Execute unit tests for build-font
        run: pnpm test:font

      - name: Create font in ./lucide-font
        run: pnpm build:font

      - name: 'Upload to Artifacts'
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: lucide-font
          path: lucide-font
