name: Lucide Vue Next checks

on:
  pull_request:
    paths:
      - packages/lucide-vue-next/**
      - tools/build-icons/**
      - tools/rollup-plugins/**
      - pnpm-lock.yaml

jobs:
  lucide-vue-next:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm --filter lucide-vue-next build

      - name: Test
        run: pnpm --filter lucide-vue-next test
