name: Pull request icon preview

on:
  pull_request:
    paths:
      - 'icons/*.svg'

permissions: {}

jobs:
  generate-changed-icons-comment:
    name: Generate Changed Icons Comment
    if: github.repository == 'lucide-icons/lucide'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: 'package.json'

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@9426d40962ed5378910ee2e21d5f8c6fcbf2dd96 # v47.0.6
        with:
          files: icons/*.svg

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
      - name: Install svgson for code preview (safer and faster than installing all deps)
        run: npm install svgson@5.3.1 --force

      - name: Save PR number
        run: |
          mkdir -p ./pr
          echo ${{ github.event.number }} > ./pr/NR

      - name: Generate comment markup
        run: node ./scripts/generateChangedIconsCommentMarkup.mts >> ./pr/comment-markup.md
        id: comment-markup
        env:
          CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: pr_number
          path: pr/
