name: Test Lucide Svelte

on:
  pull_request:
    paths:
      - packages/lucide-svelte/**
  push:
    paths:
      - packages/lucide-svelte/**

  workflow_dispatch:
    inputs:
      version:
        description: Version
        required: true

jobs:
  lucide-svelte:
    if: github.repository == 'lucide-icons/lucide'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.4.0
        with:
          node-version: "14"
          cache: yarn

      - name: Install dependencies
        run: yarn --prefer-offline

      - name: Build
        run: yarn workspace lucide-svelte build

      - name: Test
        run: yarn workspace lucide-svelte test

